### ISSUE TITLE
Unable to recognize "\ operatorname" flag

### ISSUE THREAD

**Issue by yi-Xu-0100** [osanshouo/latex2mathml#1]
I use the web to convert latex to mathml, but in my latex code, "\ operatorname" flag can not be recognized. Can you add support for this flag?

**Comment by osanshouo** [comment]
Thank you for opening issues!
It seems to be not difficult, so I'll try to implement it in a few days.

**Comment by osanshouo** [comment]
Implemented in version 0.2.1. Thank you for your suggestion!
