### ISSUE TITLE
Multi-line expression suggestion for align

### ISSUE THREAD

**Issue by yi-Xu-0100** [osanshouo/latex2mathml#2]
Multi-line expressions, e.g. \begin{align}..\end{align}. These are unsupported LaTeX commands for this project.
Can you add an option for replacing "align" to "matrix"?
This will help to show the code, not perfect, but good.

**Comment by osanshouo** [comment]
Thank you for a useful suggestion!

I confirmed that your method works, although, as you pointed out, the generated MathML is not perfect. It may be better than not-working so I've experimentally implemented it in version 0.2.1. 

I think we should use `linebreak` and `indentalign` attributes, but Firefox (Gecko) lacks [their supports](https://bugzilla.mozilla.org/show_bug.cgi?id=534962). Therefore, this hack may be the best at present. I would like to revisit it if the situation changes.
